# Generated by Django 5.2 on 2025-05-07 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="recipes",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("ingredient", models.TextField()),
                ("directions", models.TextField()),
                ("ner", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="restaurants",
            fields=[
                (
                    "restaurant_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("zip_code", models.CharField(max_length=20)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("score", models.FloatField()),
                ("category", models.TextField()),
                ("price_range", models.CharField(max_length=3)),
            ],
            options={
                "db_table": "restaurants",
            },
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
                ("tags", models.TextField(blank=True)),
                ("profile", models.TextField(blank=True)),
                ("email", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="reviews",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("stars", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.restaurants",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.users",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="menudishes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_name", models.CharField(max_length=100)),
                ("category", models.TextField(blank=True)),
                ("price", models.FloatField()),
                ("popularity_score", models.FloatField(default=0.0)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.restaurants",
                    ),
                ),
            ],
            options={
                "unique_together": {("restaurant", "menu_name")},
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("menu_name", models.CharField(max_length=100)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.recipes"
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.restaurants",
                    ),
                ),
            ],
            options={
                "unique_together": {("restaurant", "menu_name", "recipe")},
            },
        ),
    ]
