# Generated by Django 5.2 on 2025-05-07 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("recipe_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("ingredient", models.TextField()),
                ("directions", models.TextField()),
                ("ner", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="restaurants",
            fields=[
                (
                    "restaurant_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                ("zip_code", models.CharField(max_length=20)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("score", models.FloatField()),
                ("category", models.TextField()),
                ("price_range", models.CharField(max_length=3)),
            ],
            options={
                "db_table": "restaurants",
            },
        ),
        migrations.CreateModel(
            name="users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("profile", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menudish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_recipes",
                        to="users.menudish",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched_dishes",
                        to="users.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menudish",
            name="restaurant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu",
                to="users.restaurants",
            ),
        ),
        migrations.CreateModel(
            name="reviews",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("stars", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.restaurants",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="users.users",
                    ),
                ),
            ],
        ),
    ]
